import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './app/App';
import {consumePairingFragment} from './features/encryption/PairingScreen';
import { ToastProvider } from './shared/stores/toast';
import { LanguageProvider } from './shared/components/i18n/LanguageProvider';
import './styles/upstream.css';
import 'katex/dist/katex.min.css';
import './styles/workspace.css';
import './styles/chat-appearance.css';
const initialPairingFragment=consumePairingFragment();
createRoot(document.getElementById('root')!).render(<React.StrictMode><LanguageProvider><ToastProvider><App initialPairingFragment={initialPairingFragment}/></ToastProvider></LanguageProvider></React.StrictMode>);
